name: dkFieldServices
description: DIAKROS FIELD SERVICES

version: 1.0.1+37

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.7
  http: ^0.13.3
  sqflite: ^2.0.0+4
  simple_animations: ^2.4.2
  image_picker: ^0.8.4
  url_launcher: ^6.0.10
  screenshot: ^1.2.3
  social_share: ^2.1.1
  new_gradient_app_bar: ^0.2.0
  #barcode_scan_fix: ^1.0.2
  provider: ^6.0.0
  scroll_to_index: ^2.0.0
  progress_dialog: ^1.2.4
  #material_switch: ^0.0.8
  flutter_toggle_tab: ^1.2.0
  carousel_pro: ^1.0.0
  flutter_image_compress: ^1.1.0
  liquid_pull_to_refresh: ^3.0.0
  photo_view: ^0.12.0
  time: ^2.0.0
  flutter_html: ^2.1.2
  flutter_circle_color_picker: ^0.3.0
  flutter_stripe: ^9.5.0+1

    #flutter_document_picker: ^4.0.1
    #pdfx: ^2.0.1+1
    #flutter_beep: ^1.0.0
    #video_player: ^0.11.1+2
    #video_compress: ^3.1.0
# dependency_overrides:
    #   flutter_ringtone_player:
    # git:
    #       url: https://github.com/aarajput/flutter_ringtone_player.git
#       ref: 'issue/android_v2_embedding'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: "assets/launcher/icon.png"
  android: true
  ios: false

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/articulo.png
    - assets/articulo1.png
    - assets/articulo2.png
    - assets/articulo3.png
    - assets/articulo4.png
    - assets/familia.png
    - assets/logo.png
    - assets/tarjetas.png
    - assets/articuloRopa.png
    - assets/familiaRopa.png
    - assets/articuloPeluqueria.png
    - assets/familiaPeluqueria.png
    - assets/articuloFruteria.png
    - assets/familiaFruteria.png
    - assets/wasap.png
    - assets/Alergeno1.png
    - assets/Alergeno2.png
    - assets/Alergeno3.png
    - assets/Alergeno4.png
    - assets/Alergeno5.png
    - assets/Alergeno6.png
    - assets/Alergeno7.png
    - assets/Alergeno8.png
    - assets/Alergeno9.png
    - assets/Alergeno10.png
    - assets/Alergeno11.png
    - assets/Alergeno12.png
    - assets/Alergeno13.png
    - assets/Alergeno14.png



  # To add assets to your application, add an assets section, like this:
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  # PARA CAMBIAR EL ICONO LAUNCHER
  #  flutter pub get
  #  flutter pub run flutter_launcher_icons:main